apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: actions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: actions
    app.kubernetes.io/part-of: actions
  name: actionshysj
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: actions
    weight: 100
status: {}
